 Create appspec.yml for CodeDeploy
In the root of your GitHub repo, add an appspec.yml file to define how CodeDeploy will handle the deployment:

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-app

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user